### ISSUE TITLE
no targets for download specified with .phraseapp.yml

### ISSUE THREAD

**Issue by Arnotjevleesch** [francois2metz/phraseapp-docker#1]
In the dockerfile, I add my local configuration file .phraseapp.yml

```
phraseapp:
  access_token: 5c...
  project_id: 66...
  pull:
    targets:
      - file: "./messages_<locale_name>.xml"
        params:
          file_format: properties_xml`
```

next to the executable
```
FROM alpine:3.8
ENV VERSION 1.12.4
...
ADD ./.phraseapp.yml /usr/local/bin/.phraseapp.yml
```

Then, I run the pull (without volume) : 

`docker run --rm -ti --name phraseapp urm/dktconnect-phraseapp pull`

I finally obtain the error : 

`ERROR: no targets for download specified`
